'use client';
import {useEffect,useRef,useState,useMemo} from 'react';
import {ArrowUpRight,Plus,Check,Trash2,Upload,LogOut} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {analyzeImageDetails,distance,hex,hslToRgb,rgbToHsl,type RGB} from '@/lib/color';
import {configured,listPhotos,signIn,uploadPhoto,deletePhoto,type Config,type Photo} from '@/lib/collection';

export default function Collection({config,initialPhotos}:{config:Config;initialPhotos:Photo[]}){
 const connected=configured(config),[photos,setPhotos]=useState<Photo[]>(initialPhotos),[hsl,setHsl]=useState<RGB>([28,46,68]),[previewHue,setPreviewHue]=useState<number|null>(null),[picked,setPicked]=useState<string|null>(null),[hover,setHover]=useState(false),[blend,setBlend]=useState(0),[manager,setManager]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(connected),[message,setMessage]=useState(''),[token,setToken]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[pendingDelete,setPendingDelete]=useState<string|null>(null);
 const urls=useRef<string[]>([]),fileInput=useRef<HTMLInputElement>(null),thumbs=useRef(new Map<string,HTMLButtonElement>());const rgb=hslToRgb(...hsl),color=hex(rgb),displayHue=previewHue??hsl[0],displayColor=hex(hslToRgb(displayHue,hsl[1],hsl[2])),wheelBackground=`conic-gradient(from 90deg, ${[0,60,120,180,240,300,360].map(hue=>`hsl(${hue} ${hsl[1]}% ${hsl[2]}%)`).join(', ')})`;
 const sorted=useMemo(()=>[...photos].sort((a,b)=>distance(a.rgb,rgb)-distance(b.rgb,rgb)),[photos,...rgb]);
 const current=photos.find(p=>p.id===picked)||sorted[0],closest=current?[current,...sorted.filter(photo=>photo.id!==current.id)].slice(0,11):[],neighbors=current?[...closest.slice(1,6).reverse(),current,...closest.slice(6,11)]:[],frameRatio=current?.width&&current?.height?current.width/current.height:1,amount=hover?100:blend;
 useEffect(()=>{if(!current)return;thumbs.current.get(current.id)?.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'});},[current?.id]);
 useEffect(()=>{if(connected)listPhotos(config).then(cloud=>setPhotos(()=>{const merged=[...cloud,...initialPhotos];return merged.filter((photo,index)=>merged.findIndex(candidate=>photo.arena_id?candidate.arena_id===photo.arena_id:candidate.id===photo.id)===index);})).catch(e=>setMessage(e.message)).finally(()=>setLoading(false));return()=>{urls.current.forEach(URL.revokeObjectURL);};},[config.url,config.key,connected,initialPhotos]);
 const choose=(p:Photo)=>{setPicked(p.id);setHsl(rgbToHsl(p.rgb));setBlend(0);};
 const updateColor=(next:RGB)=>{setPicked(null);setHsl(next);};
 const pointerHue=(e:{currentTarget:HTMLDivElement;clientX:number;clientY:number})=>{const box=e.currentTarget.getBoundingClientRect(),x=e.clientX-box.left-box.width/2,y=e.clientY-box.top-box.height/2;return (Math.atan2(y,x)*180/Math.PI+360)%360;};
async function addFiles(files:FileList|null){if(!files?.length)return;setBusy(true);setMessage('');let count=0;const errors:string[]=[];for(const file of Array.from(files)){try{let p:Photo;if(connected){if(!token)throw new Error('Sign in to save images.');p=await uploadPhoto(config,file,token);}else{if(!['image/jpeg','image/png','image/webp','image/avif'].includes(file.type)||file.size>15*1024*1024)throw new Error(`${file.name}: use JPEG, PNG, WebP or AVIF, under 15 MB.`);const url=URL.createObjectURL(file);try{const details=await analyzeImageDetails(url);p={id:crypto.randomUUID(),title:file.name.replace(/\.[^.]+$/,''),url,rgb:details.rgb,width:details.width,height:details.height,temporary:true};urls.current.push(url);}catch(e){URL.revokeObjectURL(url);throw e;}}setPhotos(old=>[...old,p]);count++;}catch(e){errors.push((e as Error).message);}}setMessage(`${count} image${count===1?'':'s'} ${connected?'saved':'loaded for this preview'}.${errors.length?' '+errors.join(' '):''}`);setBusy(false);if(fileInput.current)fileInput.current.value='';}
 async function remove(id:string){setBusy(true);try{const p=photos.find(x=>x.id===id);if(connected&&!p?.temporary&&!p?.bundled){if(!token)throw new Error('Sign in first.');await deletePhoto(config,id,token);}setPhotos(old=>old.filter(p=>p.id!==id));setPendingDelete(null);setMessage(p?.bundled?'Image hidden for this visit.':'Image removed from the collection.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const life=new AbortController();Promise.resolve(context.registerTool({name:'select_collection_color',description:'Select a hue in the visible image collection and show the closest images.',inputSchema:{type:'object',properties:{hue:{type:'number',minimum:0,maximum:359}},required:['hue'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input:unknown){const hue=(input as {hue?:unknown})?.hue;if(typeof hue!=='number'||!Number.isFinite(hue)||hue<0||hue>359)throw new Error('Hue must be a number from 0 to 359.');setHsl(old=>[hue,old[1],old[2]]);setPicked(null);return {hue};}},{signal:life.signal})).catch(()=>{});return()=>life.abort();},[]);
 return <main className="collection-shell">
 <header className="masthead"><a className="arena-link" href="https://www.are.na/eva-li-ppue5pcryww/parsons-studio-256" target="_blank" rel="noreferrer">Are.na <ArrowUpRight size={14}/></a><button className="glass-button" onClick={()=>setManager(true)}><Plus size={15}/> Collection <span className="count">{photos.length.toString().padStart(2,'0')}</span></button></header>
 <section className="filmstrip" aria-label="Closest colors">{neighbors.length?<div className="thumbs">{neighbors.map(p=><button ref={node=>{if(node)thumbs.current.set(p.id,node);else thumbs.current.delete(p.id);}} key={p.id} className={`thumbnail ${current?.id===p.id?'selected':''}`} onClick={()=>choose(p)} title={`${p.title} · ${hex(p.rgb)}`} aria-label={`View ${p.title}`} aria-pressed={current?.id===p.id}><img src={p.url} alt={p.title}/><i style={{background:hex(p.rgb)}}/></button>)}</div>:<div className="empty-strip">{loading?'Loading your collection…':'Your images will find their place along the spectrum.'}</div>}</section>
 <section className="explorer"><div className="color-panel"><div className="section-label">01 / CHOOSE A COLOR</div><div className="wheel-wrap"><div className="color-wheel ring-wheel" role="slider" tabIndex={0} aria-label="Color hue" aria-valuemin={0} aria-valuemax={359} aria-valuenow={Math.round(hsl[0])} aria-valuetext={`${Math.round(hsl[0])} degrees, ${color}`} style={{background:wheelBackground}} onPointerMove={e=>{if(e.pointerType==='mouse')setPreviewHue(pointerHue(e));}} onPointerLeave={()=>setPreviewHue(null)} onPointerDown={e=>{if(e.pointerType!=='mouse')updateColor([pointerHue(e),hsl[1],hsl[2]]);}} onClick={e=>{const hue=pointerHue(e);setPreviewHue(hue);updateColor([hue,hsl[1],hsl[2]]);}} onKeyDown={e=>{if(['ArrowRight','ArrowUp','ArrowLeft','ArrowDown','Home','End'].includes(e.key)){e.preventDefault();updateColor([e.key==='Home'?0:e.key==='End'?359:(hsl[0]+(['ArrowRight','ArrowUp'].includes(e.key)?1:-1)*(e.shiftKey?10:1)+360)%360,hsl[1],hsl[2]]);}}}><span className="wheel-cursor" style={{left:`${50+39*Math.cos(displayHue*Math.PI/180)}%`,top:`${50+39*Math.sin(displayHue*Math.PI/180)}%`,background:displayColor}}/></div><div className="wheel-center"><i style={{background:displayColor}}/><span>{displayColor}</span><small>{previewHue===null?'SELECTED COLOR':'CLICK TO SELECT'}</small></div></div><div className="tone-controls"><span>Lightness</span><Slider aria-label="Color lightness" min={8} max={95} value={[hsl[2]]} onValueChange={v=>updateColor([hsl[0],hsl[1],Array.isArray(v)?v[0]:v])}/><span>{Math.round(hsl[2])}%</span></div><div className="tone-controls saturation"><span>Saturation</span><Slider aria-label="Color saturation" min={0} max={100} value={[hsl[1]]} onValueChange={v=>updateColor([hsl[0],Array.isArray(v)?v[0]:v,hsl[2]])}/><span>{Math.round(hsl[1])}%</span></div></div>
 <div className="photo-panel"><div className="section-label">02 / A COLOR, A MEMORY</div>{current?<><button className={`photo-stage image-stage ${frameRatio<1?'portrait':'landscape'}`} onPointerEnter={e=>{if(e.pointerType==='mouse')setHover(true);}} onPointerLeave={()=>setHover(false)} onFocus={()=>setHover(true)} onBlur={()=>setHover(false)} onClick={()=>{setHover(false);setBlend(blend===100?0:100);}} aria-label={`${current.title}. Toggle image and blended color ${hex(current.rgb)}.`} style={{background:hex(current.rgb),aspectRatio:current.width&&current.height?`${current.width}/${current.height}`:'1/1'}}><img key={current.id} src={current.url} alt={current.title} onLoad={e=>{if(current.width&&current.height)return;const width=e.currentTarget.naturalWidth,height=e.currentTarget.naturalHeight;if(width&&height)setPhotos(old=>old.map(photo=>photo.id===current.id?{...photo,width,height}:photo));}} style={{filter:`blur(${amount*.55}px)`,opacity:1-amount/100,transform:`scale(${1+amount*.003})`}}/><span className="color-reveal" style={{opacity:amount/100,color:rgbToHsl(current.rgb)[2]>58?'#222':'#fff'}}><strong>{hex(current.rgb)}</strong><small>ALL THE COLORS, BECOME ONE.</small></span></button><p className="photo-hint">Hover to dissolve. Click to keep the color.</p></>:<button className="photo-stage empty-stage" onClick={()=>setManager(true)}><div className="empty-content"><span className="empty-symbol">＋</span><h1>A collection in the making.</h1><p>{connected?'Add your first image to begin exploring.':'Your Are.na images aren’t connected yet.'}<br/>{connected?'Every photograph has a color to discover.':'Add a few images to try the experience.'}</p><span className="empty-action">{connected?'Add images':'Try your images'} <ArrowUpRight size={13}/></span></div></button>}</div></section>
 <footer><span>265ThesisBrainstormCollectionEvaLI</span><span>Objects. Places. Little things worth keeping.</span><button onClick={()=>setManager(true)} className="status-button"><i className="online"/>ARE.NA · 132 IMAGES{connected?' · CLOUD CONNECTED':''}</button></footer>
 {message&&!manager&&<div className="inline-message" role="status">{message}</div>}
 <Dialog open={manager} onOpenChange={setManager}><DialogContent className="collection-dialog"><DialogTitle>Make room for more.</DialogTitle><DialogDescription>{connected?'Add images to your collection. Each one becomes a color.':'All 132 Are.na images are included. New uploads remain temporary until Supabase is connected.'}</DialogDescription>
 {!connected&&<div className="connection-note"><span className="status-dot"/>Are.na connected · Supabase pending</div>}
 {connected&&!token?<form className="login-form" onSubmit={async e=>{e.preventDefault();setBusy(true);try{const session=await signIn(config,email,password);setToken(session.access_token);setPassword('');setMessage('Signed in.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}><label>Email<input type="email" required autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" required autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="dark-button" disabled={busy}>Sign in to manage</button></form>:<><input ref={fileInput} className="sr-only" type="file" multiple accept="image/jpeg,image/png,image/webp,image/avif" onChange={e=>void addFiles(e.target.files)}/><button disabled={busy} className="upload-area" onClick={()=>fileInput.current?.click()}><Upload size={22}/><span>{busy?'Working…':connected?'Add photographs':'Try more images'}</span><small>JPEG, PNG, WebP, AVIF · up to 15 MB each</small></button><button className="glass-button import-button" disabled><Check size={13}/> Are.na share · 132 imported</button></>}
 <div role="status" className="manager-message">{message}</div>
 {photos.length>0&&<div className="manage-list">{photos.map(p=><div className="manage-row" key={p.id}><img src={p.url} alt=""/><div><span>{p.title}</span><small>{hex(p.rgb)}{p.bundled?' · Are.na':p.temporary?' · preview':''}</small></div>{(!connected||token)&&<button aria-label={`Remove ${p.title}`} disabled={busy} onClick={()=>setPendingDelete(p.id)}><Trash2 size={14}/></button>}</div>)}</div>}
 {token&&<button className="signout" onClick={()=>{setToken('');setMessage('Signed out.');}}><LogOut size={12}/> Sign out</button>}
 <p className="manager-footnote">{connected?'Only your configured editor account can make changes.':'Cloud setup is prepared in the project. Connect Supabase to keep your collection across devices.'}</p>
 <AlertDialog open={!!pendingDelete} onOpenChange={open=>{if(!open&&!busy)setPendingDelete(null);}}><AlertDialogContent><AlertDialogTitle>Remove this image?</AlertDialogTitle><AlertDialogDescription>The image will leave this collection. Its original source file is kept.</AlertDialogDescription><div className="flex justify-end gap-3"><AlertDialogCancel disabled={busy}>Cancel</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={()=>pendingDelete&&void remove(pendingDelete)}>Remove</AlertDialogAction></div></AlertDialogContent></AlertDialog>
 </DialogContent></Dialog>
 </main>;
}
